### ISSUE TITLE
Bloat from depreciated ships, and no grouping, confusing

### ISSUE THREAD

**Issue by bugme143** [eveisesi/skillboard#6]
We can get rid of all the old-style skins of ships (ORCA Ore Development Edition, Moros Interbus Edition, etc) to simplify the data for people who are looking over the "Flyable" tab, and grouping by racial archetype will make it even easier than being forced to look all over for which ships someone can fly.

**Comment by ddouglas** [comment]
Closed with https://github.com/eveisesi/skillboard/commit/c14700cf48b3e3b8932b4a812325938336fec16b

**Comment by ddouglas** [comment]
Small note here, the change won't be reflected immediately. It'll take time to filter the unpublished ships/skills out of the database. If a character doesn't train anymore skills, then the unpublished stuff will never filter out.
